require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - dsapi.gemspec
    - Guardfile
    - vendor/bundle/**/*
    - spec/dsapi/schema/**/*

Naming/AccessorMethodName:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
